### ISSUE TITLE
Channel in node not reciving status

### ISSUE THREAD

**Issue by Fl0te** [mrgadget/node-red-contrib-hdlbus#1]
Hi.

Trying to use your fork so i can have some more functionality but have some issues.

Can turn on or off the lights but can not recive feedback when switched from DLP on wall or from nodered.
![image](https://user-images.githubusercontent.com/10758960/50656113-6ecbc280-0f92-11e9-98c8-9c3cbeb81ba3.png)
Should this not show me every change happening on dimmer with adress 1.60 and channel 1?
If i use the HDL raw node i can see it.
Do you have a example flow for recive status?

**Comment by mrgadget** [comment]
Hi - yep understand.  I don't use if from DLPs but do have one so will take a look.  This node is simply watching the network for events with op code 0x0032 (Single Channel Lighting Response) - if nothing is specified in the level field (as you're using it), it'll fire on every event seen.  

The flow you have above is the simplest flow that could be created and should output Single Channel Lighting Response message sent to 1.60, channel 1.

Try turning it on and off from another switch and see if it's fired?  If you use the raw node, what op code do you see with the events you're expecting to see this node fired for?

**Comment by Fl0te** [comment]
Hi and thanks for quick responce.

Think maby something went wrong during installation of pallete. Can see that none of the raw message contain any sender adresse, this is not expected?

Here is the 0032(50) message the dimmer outputs when i switch it to 100 from the out node. 
![image](https://user-images.githubusercontent.com/10758960/50685652-4edfe180-101a-11e9-8811-7117e75108e9.png)

Ps i get the same answerback when using the DLP or it is switched on from 12/1 sensor.

Should i try a new fresh install?

Thanks

**Comment by Fl0te** [comment]
Tried installing fresh on a new sd card. 
Installed Openhab and Nodered.
When i try to install from SSH i get
![image](https://user-images.githubusercontent.com/10758960/50693448-3e8a2f80-1037-11e9-818d-bdd16ab794d2.png)
[2019-01-04T14_13_00_581Z-debug.log](https://github.com/mrgadget/node-red-contrib-hdlbus/files/2727358/2019-01-04T14_13_00_581Z-debug.log)

Same if i try to install from Palette
![image](https://user-images.githubusercontent.com/10758960/50693662-e4d63500-1037-11e9-9b6e-8f6861795295.png)

[2019-01-04T14_28_20_424Z-debug.log](https://github.com/mrgadget/node-red-contrib-hdlbus/files/2727360/2019-01-04T14_28_20_424Z-debug.log)

Went in by smb and placed the files in a folder `\\192.168.10.93\openhabian\.node-red\node_modules`
restarted node red. And find it as installed in the manage palette with error:
![image](https://user-images.githubusercontent.com/10758960/50693802-5b733280-1038-11e9-962b-5e196743af2c.png)

**Comment by mrgadget** [comment]
I just checked and I had this package as a file dependency during development (as I was modifying this too) - if you go into `.node-red/node_modules` and run `git clone https://github.com/mrgadget/smart-bus` before install - hopefully that'll work.  If you want to do this via SMB and don't have git installed, just download the repo and dump it in `\\192.168.10.93\openhabian\.node-red\node_modules\smart-bus`.

I've made some local changes to `smart-bus` but stalled at the negotiation stages with the package owner so don't have my changes in the package yet.

If this doesn't work let me know and I'll sort it all out at a package level for you.

Cheers,
Ben.

**Comment by Fl0te** [comment]
Ahh tought it was installing your fork of the smart-bus and not the master.
Put it in manualy via SMB 
Tried installing via palette again and got:
![image](https://user-images.githubusercontent.com/10758960/50709818-5ed2e200-1069-11e9-9de9-e47f4b4a8206.png)
also tried going into the smart-bus folder via ssh after but get this error:
![image](https://user-images.githubusercontent.com/10758960/50709930-be30f200-1069-11e9-995b-75ae65ef950a.png)
if i try to enter the folder again via SMB its not there.

Thanks

**Comment by mrgadget** [comment]
Understand. Basically I’ve screwed it up :) I’ll fix the dep so it points at my fork (or update my lib to work with his new version) and come back to you. Probably a day or so sorry.

**Comment by Fl0te** [comment]
Ok. Thanks :)

**Comment by mrgadget** [comment]
Hi - sorry about the length of time that took!  Ended up doing quite a tidy-up of my random patchup code, ripping out bits that didn't serve the core purpose.

Also updated the readme to actually be useful.

npm update (from your ~/.node-red folder) should fix it - my fork of smart-bus (had to stick with my fork to keep button color and brightness) is now a discrete npm package which is listed as a dependency.  If the original smart-bus package is installed, it can be removed (smart-bus-mrgadget replaces it).

This was a fresh install via npm - hopefully it should work for you now!
![image](https://user-images.githubusercontent.com/700522/51418747-2b0bc680-1bea-11e9-845c-b83a8ca80623.png)

Let me know how you get on!

**Comment by Fl0te** [comment]
Hi. 
Thanks was able to install it fresh with no problem and everything seems to be working fine. No problem waiting.

I have one more question about the raw out node.
I am trying to send a Read status command to my outdoor sensor "(11) Sensors in One".
If i have a iridium server running i can see the request with code 0x1604 going out and the sensor responding as expected.
![outdoor sensor read status and feedback](https://user-images.githubusercontent.com/10758960/51419795-8d82a980-1b8d-11e9-8a17-81c406016e02.png)
read status: `{"sender":"253.254","target":"1.152","code":5636,"topic":"command","_msgid":"de22ce4d.97ff6"}`

feedback:
`{"sender":"1.152","target":"253.254","code":5637,"payload":{"success":true,"temperature":29,"brightness":0,"air":89,"gas":255,"movement":true,"dryContacts":[{"number":1,"status":false},{"number":2,"status":false}]},"topic":"command","_msgid":"3fa09aab.145116"}`

But i have not been able to send the same raw command to get the status here is what i tried:
![test](https://user-images.githubusercontent.com/10758960/51419900-5eb90300-1b8e-11e9-88ce-a94d70fef0a5.png)
Get this error when i try: `"Error: Data encoder for command 0x1604 is not implemented"` and no responce from the sensor. 

Can you please advice me in what i am doing wrong?
Thanks again.

**Comment by mrgadget** [comment]
Nothing you're doing wrong - the encoders/parsers are handled by the underlying smart-bus-mrgadget package.  In this case, it's missing the operation code for your sensor (this is why I forked it).

Do you have the HDL config tool?  Would be keen to get a dump of changing settings etc so I can create an encoder/parser for `0x1604` (the request) and `0x1605` (the response).

I'll have a look and see what I can find in the meantime.

**Comment by mrgadget** [comment]
Still keen to get a raw output from the HDL tool - Here's the spec for it:
![image](https://user-images.githubusercontent.com/700522/51420307-e7b75500-1bf5-11e9-8add-f516779e7c94.png)

**Comment by Fl0te** [comment]
Ok i was mistaken thought raw out would do it without having to fix the smart-bus package. 

Yes i have the tool and here is attached dump (hope this is what you are after.
 If i run the iridium server it really floods my bus so be warned.
[HDL Raw.txt](https://github.com/mrgadget/node-red-contrib-hdlbus/files/2775009/HDL.Raw.txt)
See here for timestamp:
![timestamp](https://user-images.githubusercontent.com/10758960/51420660-6b405a00-1b94-11e9-9034-5badb7d03654.jpg)
Think this is the lines you want?: 
`CRC00089 02.29.15:382 : 0B FD FE FF FE 16 04 01 98 77 7D
CRC00090 02.29.15:406 : 0D FD FE FF FE 15 CE 01 29 01 01 9E 29
CRC00091 02.29.15:434 : 18 01 98 01 4A 16 05 FD FE F8 30 00 00 59 FF FF 00 00 00 00 00 FF E5 5D`

Am i correct in asuming that for every unsuported command code i want to send it has to be added to the file `https://github.com/mrgadget/smart-bus/blob/master/lib/commands.js` to work or is it possible to send command as Hex or something?

Btw. 1.152 is the outdoor sensor and 253.254 is the iridium server.

**Comment by mrgadget** [comment]
Interesting. 0x1605 has a parser there, there's just no encoder/parser for 0x1604 - which is really simple because it doesn't appear to have any parameters.

I've updated it - can you do a `npm update` and try again please?

**Comment by Fl0te** [comment]
feel stupid now but npm update does not work for me.
![npm update](https://user-images.githubusercontent.com/10758960/51426146-95bb0300-1be6-11e9-96e2-c0e2df0fdf6b.jpg)
Tried this and i can see there is a new version but it does not want to change. Tried uninstalling it and installing again but still 1.0.3. Is there a command i need to use to force it to 1.1.2?

**Comment by Fl0te** [comment]
Got it working copying the files directly from git and copying it into the folders without npm. 
Strange thing i noticed now is that the values are wrong for temprature and movement but that is a different problem and i think it must be some scaling issue or something, will study it a bit more and check the lux in daylight.

Thanks again.
