### ISSUE TITLE
odd codes of HDL raw messages

### ISSUE THREAD

**Issue by poedator** [mrgadget/node-red-contrib-hdlbus#3]
Hi, Ben!
Thank you for the nice module! I am trying to use it to build MQTT-HDL gateway.
One issue that I have is that the messages with code 61439 (0xEFFF, relay state) only show 6 channels for 12-channel relays. In the protocol they use 2 bytes to deliver state of 12-channel relays, not one. Could you please comment on this?

**Comment by mrgadget** [comment]
Hey,

0xEFFF appears to be scene status? For the status you want 0x0033 (51) for the request, and 0x0034 (52) for the response, which includes all 12 channels (as I use a 12ch relay myself).

I use this flow for integration with Home Assistant (2-way sync with any lighting stuff)- it might contain something useful? It just watches the network for 0x0032 (50) which are the acks of `single channel lighting control` requests.
![image](https://user-images.githubusercontent.com/700522/67091986-97b00200-f20a-11e9-99e8-34b5e8c1db56.png)

The flow code is below - you should be able to just import it - you'll need to re-pick your HDL gateway and MQTT stuff.

Cheers,
Ben.

```[{"id":"4c2ba2a8.b13b5c","type":"mqtt in","z":"d2856ab9.5a3dd8","name":"from hass.io","topic":"lights/+/+/cmd","qos":"0","datatype":"auto","broker":"3ae6510.9fc8ab","x":325,"y":615,"wires":[["5a06debd.a6e9a","ff8c9a01.0c9548"]]},{"id":"ff8c9a01.0c9548","type":"function","z":"d2856ab9.5a3dd8","name":"hass > hdl","func":"if (msg.payload == \"ON\") {\n    msg.payload = 100;\n} else if (msg.payload == \"OFF\") {\n    msg.payload = 0;\n}\n    \nmsg.payload = {\n    \"address\": \"1.\" + msg.topic.split(\"/\")[1],\n    \"channel\": parseInt(msg.topic.split(\"/\")[2]),\n    \"level\": parseInt(msg.payload)\n}\nreturn msg;","outputs":1,"noerr":0,"x":640,"y":615,"wires":[["4654791.db8ed88","5a66c3d4.28de6c"]]},{"id":"5a66c3d4.28de6c","type":"hdl-channel-out","z":"d2856ab9.5a3dd8","controller":"42aa3da7.36f314","name":"to hdl","address":"1.1","channel":1,"level":"","x":890,"y":600,"wires":[]},{"id":"1586ad61.c3c5f3","type":"hdl-raw-in","z":"d2856ab9.5a3dd8","controller":"42aa3da7.36f314","name":"from hdl","x":315,"y":675,"wires":[["f1462740.2675a8"]]},{"id":"9d7789a5.920a38","type":"function","z":"d2856ab9.5a3dd8","name":"hdl > hass.io","func":"if (msg.code == 50) {\n    var out = { \n        topic: \"lights\",\n        payload: null\n    }\n    out.topic += \"/\" + msg.sender.split(\".\")[1];\n    out.topic += \"/\" + msg.payload.channel;\n    out.topic += \"/state\";\n    if (msg.payload.level === 0) {\n        out.payload = {\n            \"power\": \"OFF\",\n            \"brightness\": msg.payload.level\n        }\n    } else {\n        out.payload = {\n            \"power\": \"ON\",\n            \"brightness\": msg.payload.level\n        }\n    }\n}\nreturn out;","outputs":1,"noerr":0,"x":640,"y":675,"wires":[["4139b534.a1493c","45bf119b.5722f"]]},{"id":"45bf119b.5722f","type":"mqtt out","z":"d2856ab9.5a3dd8","name":"to hass.io","topic":"","qos":"1","retain":"true","broker":"3ae6510.9fc8ab","x":900,"y":690,"wires":[]},{"id":"4139b534.a1493c","type":"debug","z":"d2856ab9.5a3dd8","name":"hass output","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":910,"y":645,"wires":[]},{"id":"5a06debd.a6e9a","type":"debug","z":"d2856ab9.5a3dd8","name":"from hass.io","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":640,"y":570,"wires":[]},{"id":"960c051a.d0ba28","type":"debug","z":"d2856ab9.5a3dd8","name":"from hdl","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"payload","targetType":"msg","x":630,"y":720,"wires":[]},{"id":"4654791.db8ed88","type":"debug","z":"d2856ab9.5a3dd8","name":"hdl output","active":false,"tosidebar":true,"console":false,"tostatus":false,"complete":"true","targetType":"full","x":900,"y":555,"wires":[]},{"id":"f1462740.2675a8","type":"function","z":"d2856ab9.5a3dd8","name":"filter","func":"if (msg.code == 50) {\n    return msg;\n}","outputs":1,"noerr":0,"x":470,"y":675,"wires":[["960c051a.d0ba28","9d7789a5.920a38"]]},{"id":"3ae6510.9fc8ab","type":"mqtt-broker","z":"","name":"mqtt","broker":"mqtt.home.local","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""},{"id":"42aa3da7.36f314","type":"hdl-controller","z":"","host":"10.8.8.255","port":"6000","subnetid":"1","deviceid":"98","broadcast":true,"daliId":"20"}]```

**Comment by poedator** [comment]
Ben, thanks for the quick response. I already figured codes 51-52 but I like your flow code better.
What I am trying to do is to capture the channel changes after scene commands. They would not be reported by code 50 (single channel response). Instead they are included as bits in codes 0x0003 and 0xEFFF. So my choices are: 1) decode 0x0003 or 2) send 0x0033 (51) every time there is code 0x0003 incoming.
The ["HDL-BUS control and operate code" ](https://raw.githubusercontent.com/estbeetoo/node-red-contrib-hdl/master/doc/HDL-BUS%20Pro%20operation%20codes(Eng)%20Jan%2008%202013.pdf) reference states for 0x0003: "Area number(1B); Scene number(1B); channels total number(1B); status of channel switch(n Bit),n-means how many channels". Same for 0xEFFF.
The picture from the HDL tool below shows the status bits highlighted:
![channel_bits](https://user-images.githubusercontent.com/24738311/67129346-199e2c00-f207-11e9-8e9c-2a14c738d73b.png)

I did pull this info in the past with a python parser but now I move my gateway to node_red so I'd be grateful for a bit of help from you...

**Comment by poedator** [comment]
I did more tests of handling of code 0x0003: sometimes it returns 12 channels values, but sometimes just 8. See pic: 
![just8](https://user-images.githubusercontent.com/24738311/67130607-88c94f80-f20a-11e9-9ecf-05ec68a2b7d5.PNG)
When testing 0xEFFF I see 5 6 or 7 values returned... Never 12.

**Comment by mrgadget** [comment]
I see what you're getting at.  I don't use scenes at the moment - I'll configure one up and have a play.  I'd say it'll be the underlying library as it just presents objects back to me which I output with the nodes.

**Comment by poedator** [comment]
OK, I will check the underlying library code too.
Try scenes, they are much faster than series of single channel commands to same relay.

**Comment by poedator** [comment]
please accept my commit from here: https://github.com/mrgadget/smart-bus/pull/2

**Comment by mrgadget** [comment]
Hey - sorry I missed your message from 4 days ago.  I have merged your PR, incremented the version number and published to npm.  You should see the new version available in node-red shortly.  Thanks for sorting this one out, appreciate the assist!

**Comment by poedator** [comment]
closed with commit mrgadget/smart-bus#2
