### ISSUE TITLE
Commands generate no response on HDL smart-bus

### ISSUE THREAD

**Issue by jrstrengen** [mrgadget/node-red-contrib-hdlbus#4]
Hi, 
I'm all new to node-red, trying to get node-red-contrib-hdlbus to work.
This module looks like the most promising user-friendly version of the ones currently available.

I've come so far that i see the the packages being delivered on the bus, with the correct values, but nothing happens, and I get no response that a setting have been set.
Testing with a single light controller to turn on a light on a dimmer module.

I've added the Command test output from setup tool.
00072  09:37:51:805 : 0F FA 63 FF FE 00 31 01 15 03 64 00 00 31 78     Single Channel Control Chn No.-3;Intensity-100   250-99--Unname  ---> 1-21-Dimmer 2
00073  09:38:52:836 : 0F FD FE FF FE 00 31 01 15 03 64 00 00 CE 24     Single Channel Control Chn No.-3;Intensity-100   253-254--Unname  ---> 1-21-Dimmer 2
00074  09:38:52:881 : 10 01 15 02 6D 00 32 FF FF 03 F8 64 06 04 B8 9B     Response single channel control Chn No.-3;Intensity-100   1-21-HDL-MDT0601.433-Dimmer 2

First line is the command from node-red, the second in a manual command from the command test, to show what i would expect to happen. 

Any help apreciated.

Regards,
Robert

**Comment by jrstrengen** [comment]
Never mind, this was a configuration issue on my side.
Sending commands to the workstation that runs HDL software will detect the commands(in the command-tool), but they are ofc not on the bus, so the devices will not see them.

Looking up the correct IP from the IP-module and not options made the initial tests work.

**Comment by mrgadget** [comment]
I like issues like this one!

On the IP front - I've found enabling broadcast, and using the network broadcast address works best (especially if you have other devices wanting to listen to traffic).

ie, if your address is 192.168.1.250/24 (255.255.255.0 mask), in Node-Red, try using 192.168.1.255 for your module address.

**Comment by jrstrengen** [comment]
Its good when issues are user-errors fixed by the user.
I have hope for this project, as I find the price for irdium mobile a little too steep based on what you get for it as a mobile platform. 

The network broadcast address made wonders for both receiving values and uv switches.
I finally understood  that every single command is broadcasted on the IP-network as UDP, and not actually by sending commands to the IP-gateway like an API. 
This is both nice for third party integrations, but a little scary from a security point of view.
Understanding this, made wonders for an infrastructure guy like me.

And if anyone else reads this and use node-red in a docker container, then the container needs to be created with network-mode=host to be able to relay every packet into the container for node-red to pick it up.
